sudo: required

services:
  - docker

matrix:
include:
  - language: java
    script: cd server && mvn clean test

  - language: nodejs
    before_script:
      - cd client && npm install
    script:
      - cd client && npm run test