cache:
  directories:
  - $HOME/.m2
  - client/node_modules

matrix:
  include:
  - language: java
    jdk: oraclejdk11
    sudo: required
    services:
      - docker
    script: cd server && mvn clean test

  - language: nodejs
    before_script:
      - cd client && npm install
    script:
      - npm run test